language: objective-c
osx_image: xcode7.2
#before_install:
#  - brew update
#  - brew install carthage
before_script:
  - carthage bootstrap
before_deploy:
  - carthage build --no-skip-current

cache: cocoapods
# podfile: Example/Podfile

# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

script:
# TODO: Build the CocoaPods project
# - set -o pipefail && xcodebuild -workspace Example/xDripG5.xcworkspace -scheme xDripG5-Example -sdk iphonesimulator -destination name="iPhone 6" ONLY_ACTIVE_ARCH=NO | xcpretty
- xctool -project xDripG5.xcodeproj -scheme xDripG5 -sdk iphonesimulator9.2 build test
- pod lib lint --allow-warnings
